# Local Variables:
# ispell-local-dictionary: "espanol"
# End:

#+LANGUAGE: es

* termo
** conferencias
*** prueba1
**** clase 2

  [2020-05-08 vie 10:50]

  Las grabaciones no involucran los repasos por el peso de las
  grabaciones.

***** Repaso clase pasada

  Equilibro térmico vs termodinámico

  Adiabático. Permeabilidad.

  Definir un sistema en función de las 3 fundamentales:
  - Temperatura
  - Presión
  - Volumen.
  
  Estados y procesos termodinámicos.

  - Isobárico, iso-aquí, iso-acá
  - Reversible e irreversible
  - Cuasi-estático?

***** Clase
  Ley cero.
  Fuente: LEY CERO_U1.pdf (campus virtual)
  Indagaron harto en el punto triple.


  Seguimiento Clase 2

**** clase 3

  [2020-05-14 jue 09:00]

  Ejercicio
  - punto triple
  - física2

  PPT Intercambio de calor sensible

**** clase
  [2020-05-28 jue]

  Concepto de trabajo (en forma de integral).

  Campus PDF:
  TRABAJO_U2.pdf

**** clase [2020-07-23 Thu] 
     
    2da ley de la termodinámica. 
    Balance de energía en sistema aislados, cerrados y abiertos.

    Una palabra sobre el volumen de control (no cambia).
    
** evaluaciones
   
   Todas las fechas cambiaron por paro.
   
*** prueba1
    
    Temario en campus.
    El jueves previo es consultas antes de la prueba1.
    Prueba el próximo viernes en la mañana.

*** comentarios evaluaciones
    
    La prueba1 puede ser en pareja o individual. +La prueba1 se cambió del 12 al 19+.
