# Local Variables:
# ispell-local-dictionary: "espanol"
# End:

#+LANGUAGE: es

* opti
** probando notación LaTeX

   La ultima línea.

   Esto \( a=b \) debería ser una ecuación.

   Estas deberían ser varias ecuaciones.

   \begin{equation}
   x=\sqrt{b}
   \end{equation}

   If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].


** Conferencias
***  prueba1
**** 1 intro y forma estándar
- Presentación de la asignatura, requerimientos básicos, fechas, etc.

  Diferenciación entre notación canónica y estándar.

**** 2 modelación1
     Ejemplos de como modelar problemas estáticos y dinámicos.
**** 3 modelación2
     Más problemas.
**** 4 solución gráfica
     - Conjunto factible
     - Función objetivo
     - Solución gráfica
**** 5 convexidad y puntos extremales

    
**** 6 direcciones extremales

     Teorema de Caratheodory.

     Video: IMA300 25 de mayo_2.mp4 : 22:33 minutos.

** fecha evaluaciones

*** prueba1
Lunes 8 de junio 2020 (.35)
*** prueba2
Lunes 20 de julio 2020 (.30)
*** prueba3
Lunes 17 de agosto 2020 (.35)
*** examen
Lunes 31 de agosto 2020
*** comentario evaluaciones
Cuando empiezan las clases presenciales, empiezan las pruebas presenciales.
