#+TITLE: Resistencia de Materiales
#+SETUPFILE: ~/Downloads/org-html-themes/setup/theme-readtheorg.setup
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :university:

* Resistencia de Materiales
** Horario
*** Ayudantia
    Viernes por medio, 15:40 horas
    Mismo link de clases
    Mañana viernes 13 de nov primera ayudantía
** Links
*** Cátedra y ayudantía
    - https://reuna.zoom.us/j/89482086920?pwd=bFZtWUpqZ2hoaW5KaGFTSkRrakFTUT09
** Evaluación :exam:
*** DONE prueba1
    CLOSED: [2021-01-12 Tue 01:11] DEADLINE: <2021-01-07 Thu 08:30>
    :LOGBOOK:
    - State "DONE"       from              [2021-01-12 Tue 01:11]
    :END:
*** DONE prueba2
    CLOSED: [2021-01-12 Tue 10:36] DEADLINE: <2021-01-12 Tue 08:30>
    :LOGBOOK:
    - State "DONE"       from              [2021-01-12 Tue 10:36]
    :END:
    Desde semana 4 (corresponde a clase 8) hasta última de diciembre (corresponde a clase 13).
**** clase 8: deformación
     Cuando se le aplica fuerza a un objeto y producto de ello éste cambia su forma.

***** Deformación unitaria normal
      Cuánto varía una distancia entre dos puntos de una recta.
      #+begin_center
      \[
      \epsilon_{promedio}=\frac{Variación}{Distancia\ inicial}
      =\frac
      {\Delta s' - \Delta s}
      {\Delta s}
      \]

      donde \(\ \Delta s'\ \) es la distancia final y \(\ \Delta s \ \) es la distancia inicial.

      Y si despejamos para \(\Delta s' \) tenemos:
      \[
      \boxed{\Delta s' = (1 + \epsilon ) \Delta s}
      \]

      Este despeje lo hace el profesor y es conveniente tenerlo a mano.
      #+end_center

***** Deformación unitaria cortante
      Para este se ocupan 3 puntos que forman una dupla de rectas perpendiculares. Luego, la /deformación unitaria cortante/ se calcula restando el ángulo inicial, 90° menos el ángulo final.

      #+begin_center
      \[
      \gamma= \frac{\pi}{2} - \theta'
      \]

      donde \(\ \pi/2 \ \) sería  \(\theta_0\): ángulo inicial y \(\theta'\) el ángulo final entre las rectas originalmente perpendiculares.
      #+end_center


      Observación: contrario al cálculo común de variaciones, en este caso la variación se toma como "inicial menos final" en vez del común "final - inicial". Esto probablemente se debe a la conveniencia de signos.

**** clase 9: combinando deformación con esfuerzo
     La clase 7 fue de esfuerzo, evaluado en prueba 1.
***** Ensayo de tracción y compresión
****** Esfuerzo
       #+begin_center
       \begin{align*}
 \sigma=\frac{P}{A_0}
       \end{align*}
       #+end_center

****** Deformación
       #+begin_center
       \begin{align*}
 \epsilon=\frac{\delta}{L_0}=
       \frac
       {\Delta s' - \Delta s}
       {\Delta s}
       \end{align*}
       #+end_center
****** Ley de Hooke
       <<Thomas Young>> La primera sección del gráfico de esfuerzo vs deformación, conocido como esfuerzo elástico, es una recta. Dicha recta se puede representar de la siguiente forma:
       #+begin_center
       \begin{align*}
       \sigma = E\ \epsilon
       \end{align*}

       donde \(E\ \) es una constante de proporcionalidad llamada módulo de Young, en honor a  Thomas Young.
       #+end_center

       \(E\ \) habla acerca de cuánto esfuerzo puede soportar un material antes de deformarse en extremo. Materiales muy rígidos como el acero, tienen valores grandes, mientras que materiales mas blandos como la esponja o la goma, presentan valores mas bajos.

**** clase 10: Razón de Poisson:
      Consideremos el efecto que ocurre cuando se alarga un cilindro; aumenta el largo, a costa de disminuir su diámetro, y viceversa cuando se comprime; disminuye su largo a costa de aumentar el diámetro.

      La relación entre la deformación longitudinal y diametral (lateral) de la deformación del cilindro se puede representar de la siguiente forma:

      #+begin_center
      \begin{align*}
      \nu
      = -\; \frac
      {\epsilon_{lateral}}
      {\epsilon_{longitudinal}}
      \end{align*}

      Se descompone es sus componentes dimensionales para calcular. Para la mayoría de los sólidos varía entre \(1/4\) y \(1/3\).
      #+end_center

      Al igual que la [[Thomas Young][constante de Young]], esta constante es propia para cada material. Representa la relación entre la deformación longitudinal y lateral de cada material. Nótese la relación negativa entre la longitudinal y lateral.

      Asumiendo un cilindro con eje en la dirección \( x \) y radio en la dirección \( r \) la misma ecuación se puede escribir como:

      #+begin_center
      \begin{align*}
      \nu
      = -\; \frac
      {\epsilon_{r}}
      {\epsilon_{x}}
      \end{align*}
      #+end_center

*** prueba3
    DEADLINE: <2021-03-02 Tue>
*** taller2
    <2021-01-20 Wed>
*** taller3
    <2021-01-27 Wed>
    Opcional, pero mejor darlo igual.
** Contacto
*** Profe
    Ignacio Ríos
    ignacio.rios@ufrontera.cl
    ICI-M
** Local variables :noexport:
   # Local Variables:
   # ispell-local-dictionary: "espanol"
   # End:
