#+TITLE: Investigación Operacional
#+SETUPFILE: ~/Downloads/org-html-themes/setup/theme-readtheorg.setup
#+EXCLUDE_TAGS: noexport
#+filetags: :university:

* Contenidos
** Prueba1
*** Mon Nov  2 08:33:12 2020
    Primera clase
    Lunes clase de repaso
**** Repaso
     - Materia de optimización
     - Repaso PL
       - Continuidad
       - Proporcionalidad
       - Aditividad
       - No negatividad
       - Determinismo
     - Función de ganancia (objetivo)

       \[
       Z = Ganancia - Costos \\
       ; Costos = mano de obra, materia prima
       \]

     - Matrices
     - Método gráfico
     - Repasamos simplex, dos fases y dual
     - Vemos big M method
     - Veremos problemas de transporte igualmente

     - minimización = isocosto
     - maximización = isoganancia

***** CANCELED big M method
      CLOSED: [2020-11-27 Fri 23:36]
      :LOGBOOK:
      - State "CANCELED"   from "TODO"       [2020-11-27 Fri 23:36] \\
        supongo que al saber 2 fases estas listo...?; hay algo que el gran M entrega que el dos fases no?
      :END:

      Mismo propósito de método de dos fases.

***** TODO excel como calculadora para simplex: solver
**** próxima clase
     Jueves a las 0830
     Tema: excel.
*** Mon Nov  9 08:04:57 2020
**** PPT
     - Análisis de dualidad y sensibilidad
     - Optimización lineal.
** Ayudantía
*** Carpeta Google Drive
    https://drive.google.com/drive/folders/1sw44-YOjSPYNX4SZ6XreFvnGsHAWEFZG
*** Método de 2 fases
    Después de pasar a forma estándar:

**** Fase 1

     1) \(min\quad z=\sum A_i\)
     2) Convertir las columnas de auxiliares en su correspondiente columna de variable básica\\
        Para esto simplemente hay que sumar las filas.
     3) Iterar como simplex
     4) Dos posibles resultados
        - Fila del z queda igual que al inicio pero con \(\bar z=0\)\\
          El problema es tiene solución.
        - Fila del z _no_ queda igual que al inicio, independiente del valor de \(\bar z\)\\
          El problema no tiene solución (o quizás no tiene solución usando las herramientas conocidas hasta ahora?).
     5) Suponiendo que tiene solución\\
        Pasamos a fase 2.


**** Fase 2
    
     1) Eliminar columnas de auxiliares
     2) Reemplazar fila del \(z\) actual con función objetivo original
     3) Establecer columnas de variables básicas\\
        Nuevamente, fila de variable básica \(\rightarrow\) \(1\) en su fila y \(0\) en todas las demás hacia abajo y arriba.
     4) Resolver por simplex

     En otras palabras, la fase 1, entre otras cosas, modifica las filas de restricciones y luego la fase 2 se aprovecha de esas modificaciones para resolver por simplex, con certeza de existencia de una solución.

** Resumen
   - Sensibilidad y dualidad
     - Recopilar datos de tabla inicial y tabla óptima


   Obtener el b inicial: correspondiente a la columna de limites de restricciones.
  
       - Obtener bases de tabla óptima


   Obtener el Cb: teniendo la base de la tabla óptima, se puede determinar el \(Cb\), que corresponde a los valores en \(Z\) de la tabla inicial para las bases de la tabla óptima. Ejemplo, si en la tabla óptima, la base es x2 y x3, entonces el Cb corresponde a los valores correspondientes a esas columnas de la tabla inicial en la fila del Z.

   Obtener el B: Exactamente el mismo procedimiento para obtener la base B. La diferencia es que en vez de seleccionar una fila, se selecciona la matriz. Ejemplo, si la tabla óptima entrega como bases x2 y x3, entonces la matriz base se obtiene a partir de la matriz debajo del x2 y x3 de la tabla inicial.

   Obtener el B^-1: invertir la B obtenida antes. _No_ es recomendable obtener el B-1 por otros métodos pues la información puede no estar completa, mientras que si lo obtenemos a partir del B, la información la obtenemos sin obstrucciones.


* Horario :schedule:
** Cátedra
*** Lunes 08:00 a 10:40
    - Originalmente de 08:30 a 10:40, pero teníamos conflicto de horario con otros ramos.
    https://reuna.zoom.us/j/85818738252?pwd=QVFaMkhRcmVCS1Jaa1docTI1Wmtxdz09

*** Lunes 11:00 a 13:00 (opcional, otro módulo)
    https://reuna.zoom.us/j/87913696867pwd=cWUvTnBDb0R6U2xFZW9YQ0JUbGcyQT09

*** Jueves 08:30 a 10:40 (cancelada)
    - Por conflicto de horario se cancela y se hace una clase larga el lunes.
    https://reuna.zoom.us/j/88983963727?pwd=N2dlYmpLVTlrdnV4cngzZ05NTlI5dz09

** Ayudantía
   Jueves 10:00
   https://reuna.zoom.us/j/89833514729
* Evaluación :exam:
*** TODO [#A] prueba1 5 dic
*** TODO prueba2 23 ene 2021
*** DONE taller1 14 nov
    CLOSED: [2020-11-23 Mon 18:04]
    :LOGBOOK:
    - State "DONE"       from              [2020-11-23 Mon 18:04]
    :END:
*** TODO [#A] taller2 28 nov
*** TODO taller3 19 dic
*** TODO taller1 11 ene
* Vocabulario
  - Estadigrafo de certeza?
  - Isocosto, isoganancia
  - precio sombra?
    Algo de costo de oportunidad por producto no utilizado o algo así.

* Local variables :noexport:
  # Local Variables:
  # ispell-local-dictionary: "espanol"
  # End:
