:PROPERTIES:
:ID:       66084b32-f346-448c-af75-cbdc181bef78
:END:
#+TITLE: Apuntes
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :university:notes:

* TOC :TOC_2:noexport:
- [[#apuntes][Apuntes]]
  - [[#general][General]]
  - [[#2021-05-06-thu-clase][[2021-05-06 Thu] Clase]]
  - [[#2021-05-11-tue-clase][[2021-05-11 Tue] Clase]]
  - [[#2021-05-14-fri-ayudantía][[2021-05-14 Fri] Ayudantía]]
  - [[#2021-05-18-tue-clase][[2021-05-18 Tue] Clase]]
  - [[#2021-05-20-thu-clase][[2021-05-20 Thu] Clase]]

* Apuntes
** General
*** DONE prueba2
    CLOSED: [2021-01-12 Tue 10:36] <2021-01-12 Tue 08:30>
    :LOGBOOK:
    - State "DONE"       from              [2021-01-12 Tue 10:36]
    :END:
    Desde semana 4 (corresponde a clase 8) hasta última de diciembre (clase 13 creo?).
**** clase 8: deformación
     Cuando se le aplica fuerza a un objeto y producto de ello éste cambia su forma.

***** Deformación unitaria normal
      Cuánto varía una distancia entre dos puntos de una recta.
      #+begin_center
      \[
      \epsilon_{promedio}=\frac{Variación}{Distancia\ inicial}
      =\frac
      {\Delta s' - \Delta s}
      {\Delta s}
      \]

      donde \(\ \Delta s'\ \) es la distancia final y \(\ \Delta s \ \) es la distancia inicial.

      Y si despejamos para \(\Delta s' \) tenemos:
      \[
      \boxed{\Delta s' = (1 + \epsilon ) \Delta s}
      \]

      Este despeje lo hace el profesor y es conveniente tenerlo a mano.
      #+end_center

***** Deformación unitaria cortante
      Para este se ocupan 3 puntos que forman una dupla de rectas perpendiculares. Luego, la /deformación unitaria cortante/ se calcula restando el ángulo inicial, 90° menos el ángulo final.

      #+begin_center
      \[
      \gamma= \frac{\pi}{2} - \theta'
      \]

      donde \(\ \pi/2 \ \) sería  \(\theta_0\): ángulo inicial y \(\theta'\) el ángulo final entre las rectas originalmente perpendiculares.
      #+end_center


      Observación: contrario al cálculo común de variaciones, en este caso la variación se toma como "inicial menos final" en vez del común "final - inicial". Esto probablemente se debe a la conveniencia de signos.

**** clase 9: combinando deformación con esfuerzo
     La clase 7 fue de esfuerzo, evaluado en prueba 1.
***** Ensayo de tracción y compresión
****** Esfuerzo
       #+begin_center
       \begin{align*}
 \sigma=\frac{P}{A_0}
       \end{align*}
       #+end_center

****** Deformación
       #+begin_center
       \begin{align*}
 \epsilon=\frac{\delta}{L_0}=
       \frac
       {\Delta s' - \Delta s}
       {\Delta s}
       \end{align*}
       #+end_center
****** Ley de Hooke
       <<Thomas Young>> La primera sección del gráfico de esfuerzo vs deformación, conocido como esfuerzo elástico, es una recta. Dicha recta se puede representar de la siguiente forma:
       #+begin_center
       \begin{align*}
       \sigma = E\ \epsilon
       \end{align*}

       donde \(E\ \) es una constante de proporcionalidad llamada módulo de Young, en honor a  Thomas Young.
       #+end_center

       \(E\ \) habla acerca de cuánto esfuerzo puede soportar un material antes de deformarse en extremo. Materiales muy rígidos como el acero, tienen valores grandes, mientras que materiales mas blandos como la esponja o la goma, presentan valores mas bajos.

**** clase 10: Razón de Poisson:
     Consideremos el efecto que ocurre cuando se alarga un cilindro; aumenta
     el largo, a costa de disminuir su diámetro, y viceversa cuando se comprime;
     disminuye su largo a costa de aumentar el diámetro.

     La relación entre la deformación longitudinal y diametral (lateral) de la
     deformación del cilindro se puede representar de la siguiente forma:

     #+begin_center
     \begin{align*}
     \nu
     = -\; \frac
     {\epsilon_{lateral}}
     {\epsilon_{longitudinal}}
     \end{align*}

     Se descompone es sus componentes dimensionales para calcular. Para la
     mayoría de los sólidos varía entre \(1/4\) y \(1/3\).
     #+end_center

     Al igual que la [[Thomas Young][constante de Young]], esta constante es propia para cada
     material. Representa la relación entre la deformación longitudinal y
     lateral de cada material. Nótese la relación negativa entre la longitudinal
     y lateral.

     Asumiendo un cilindro con eje en la dirección \( x \) y radio en la
     dirección \( r \) la misma ecuación se puede escribir como:

     #+begin_center
     \begin{align*}
     \nu
     = -\; \frac
     {\epsilon_{r}}
     {\epsilon_{x}}
     \end{align*}
     #+end_center

*** CANCELED prueba3
    CLOSED: [2021-03-02 Tue 11:45]
    :LOGBOOK:
    - State "CANCELED"   from "TODO"       [2021-03-02 Tue 11:45] \\
      Fuck it
    :END:
    <2021-03-02 Tue>
*** DONE taller2: listo, enviar hoy.
    CLOSED: [2021-01-20 Wed 23:18]
    :LOGBOOK:
    - State "DONE"       from "TODO"       [2021-01-20 Wed 23:18] \\
      Envia3
    :END:
    <2021-01-20 Wed>\\
    Segunda lectura complementaria.
**** Concentraciones de esfuerzos

     Desde el inicio del curso se ha hablado de esfuerzos normales y cortantes
     para diferentes geometrías. Más aún, estos esfuerzos son considerados
     uniformes, por lo que los cálculos no involucran sumas de elementos
     infinitesimales y se reducen a que el esfuerzo \(\sigma\) es directamente
     proporcional a la fuerza aplicada \(F\) e inversamente proporcional al
     área \(A\) donde se aplica dicha fuerza:

     \[
     \sigma=\frac{F}{A}
     \]

     Sin embargo, esto en realidad es una simplificación conveniente de la
     realidad, pues lo que ocurre en efecto es que se considera un esfuerzo
     \(\sigma\) como un esfuerzo promedio \(\sigma = \sigma_{promedio}\).

     En esta sección se explica el comportamiento del esfuerzo en zonas donde
     justamente, este esfuerzo no puede ser catalogado como uniforme. Esta
     situación ocurre específicamente en puntos cercanos al punto de aplicación
     de la fuerza, lo que provoca que el esfuerzo se distribuya de forma _no_
     uniforme.

     Empíricamente se observa que generalmente, la distancia para que el
     esfuerzo se asuma efectivamente uniforme debe ser por lo menos igual a la
     mayor distancia transversal a la que se aplica la fuerza \(F\), medida
     desde el punto de aplicación de la fuerza. Dicho en otras palabras, es
     muy seguro que el esfuerzo a distancias menores a la mayor distancia
     transversal a la que se aplica una fuerza \(F\), el esfuerzo transversal
     no sea uniforme.

     De esta idea también se desprende que el esfuerzo va a ser máximo donde la
     sección transversal sea mínima.

     Combinando todo tenemos que existe el cálculo de un esfuerzo promedio
     junto con el cálculo de un esfuerzo máximo que depende del área
     transversal cargada. Esta combinación recibe un nombre que ayuda a tener
     una idea de la relación entre el esfuerzo máximo localizado en un punto y
     el esfuerzo promedio en todo el cuerpo que sufre un material cuando se le
     aplica una fuerza.

     #+begin_center
     \[
     K=\frac
     {\sigma_{max}}
     {\sigma_{promedio}}
     \]
     donde \(K\) se conoce como *factor de concentración de esfuerzos*.
     #+end_center

*** CANCELED taller3
    CLOSED: [2021-05-06 Thu 17:23]
    :PROPERTIES:
    :ID:       d7c17032-4c4d-41d9-ab1b-06d50e3fe8db
    :END:
    :LOGBOOK:
    - State "CANCELED"   from "TODO"       [2021-05-06 Thu 17:23]
    :END:
    <2021-01-27 Wed 08:30>
    Opcional, pero mejor darlo igual.
** [2021-05-06 Thu] Clase
   :PROPERTIES:
   :ID:       a86b24d7-98f8-4c69-aee3-017e67f0d6ca
   :END:
   - Esfuerzo y deformación, conceptos clave del ramo.
   - Ahora se profundiza.
   - Diagrama esfuerzo vs deformación unitaria.
     \[
     \frac
     {\sigma}
     {\epsilon}
     =
     \frac
     {\text{esfuerzo}}
     {\text{deformación}}
     \]
     La primera sección del gráfico se comporta lineal.
   - La clase termina en Ley de Hooke.

** [2021-05-11 Tue] Clase
   :PROPERTIES:
   :ID:       aa793541-239f-4295-b84f-af04cdd16443
   :END:
   - [[id:a96cd3b1-580e-4bf2-814f-cb0b102dc229][log]]



   - Razón de Poisson
   - Diagrama esfuerzo --- deformación unitaria cortante
** [2021-05-14 Fri] Ayudantía
   :PROPERTIES:
   :ID:       245afd7e-df50-4e2c-aa91-be01fe9ebd0d
   :END:
   - [[id:b6a61478-c279-4af2-8365-a934b5781448][log]]

   - Deformación unitaria cortante
   - Ejercicio relación de Poisson en la deformación de un tubo
     - Alrededor de [2021-05-14 Fri 19:40]
*** [2021-05-14 Fri 19:42] Ejercicio 6 guía 6
    - [2021-05-14 Fri 19:45] Preámbulo
    - [2021-05-14 Fri 19:46] Empieza [[id:c20f40ee-6022-46b6-ba3e-e0a6417d3ab8][desarrollo]]
    - [2021-05-14 Fri 19:49] 1 MPa = 1 N/mm^2
    - [2021-05-14 Fri 19:53] Comentario sobre Ley de Hooke.
    - [2021-05-14 Fri 19:54] Análisis gráfico.
    - [2021-05-14 Fri 20:00] Épsilon permanente (paralelo a la linea inicial)
      - Obteniendo el épsilon podemos obtener la deformación unit permanente.
    - [2021-05-14 Fri 20:00-20:20] Comentarios sobre materia, aclaraciones de dudas.
**** Desarrollo
     :PROPERTIES:
     :ID:       c20f40ee-6022-46b6-ba3e-e0a6417d3ab8
     :END:
     1) Diagrama esfuerzo-deformación
        Se completa el gráfico con los datos que nos dan y vamos resolviendo
        para ecuaciones lineales.
     2) Análisis gráfico
        Teniendo los datos se empiezan a hacer conclusiones.
     3) Se obtienen otros datos, como la deformación unitaria permanente a
        partir del épsilon permanente y la longitud final después de la
        deformación.

** [2021-05-18 Tue] Clase
   :PROPERTIES:
   :ID:       b21e2950-d068-476a-942f-b50e3d9461dd
   :END:
   - [[id:0881f1cb-9fe5-47da-8450-bfadaabe4cba][log]]


   - Clase de hoy: carga axial.


   - Inicio cerca de [2021-05-18 Tue 08:40]

   - [2021-05-18 Tue 08:44] La clase anterior se vio esfuerzo y deformación
     -> propiedades relacionadas.
     + Ley de Hook
     + Razón de Poisson

   - [2021-05-18 Tue 08:46] Clase de hoy: fuerza normal: aka carga axial.
   - [2021-05-18 Tue 08:46] Al final torsor (4-6 clases) Moment flector y fuerza
     cortante.
   - *_[2021-05-18 Tue 08:53-08:56] Ecuación de deformación !!_*: presentación y
     análisis.
   - [2021-05-18 Tue 08:56-09:00] Cosas a considerar respecto de la ecuación.
   - *_[2021-05-18 Tue 09:05-09:35] Ejemplo._*
     + [2021-05-18 Tue 09:35-09:37] Recap
     + [2021-05-18 Tue 09:37] Gráfico de fuerzas
   - *_[2021-05-18 Tue 09:46-10:00] Ejemplo2_*
   - [2021-05-18 Tue 10:02]Comentarios finales y fin.

** [2021-05-20 Thu] Clase
   :PROPERTIES:
   :ID:       78b49086-ffc6-4b60-994b-01bf79ea4ff6
   :END:
   - [[id:415fd1bf-6408-44fc-a7fe-4f2af2cbeac7][log]]


   - *_[2021-05-20 Thu 17:05] Inicio_*
   - [2021-05-20 Thu 17:07] Elemento cargado axialmente estáticamente
     indeterminado.
     + Obtenemos mas incógnitas que ecuaciones, el objetivo es encontrar
       otra ecuación para poder resolver el problema.
     + Se encuentra en la condición geométrica de la deformación.
       - [2021-05-20 Thu 17:09]
       - No siempre es la misma ecuación, pero siempre surge de la geometría
         de la deformación.
     + [2021-05-20 Thu 17:15] Gráfico de deformación.
       - Lo hicimos la clase anterior:
         + Desplazamiento \(x\) vs deformación \(\delta\) (en eje vertical).
   - *_[2021-05-20 Thu 17:17] Ejemplo_*
     + [2021-05-20 Thu 17:22] Misma cosa: faltan ecuaciones.
     + [2021-05-20 Thu 17:23] Se obtiene la otra desde la geometría de la
       deformación.
     + [2021-05-20 Thu 17:35] Gráfico de deformación.
   - *_[2021-05-20 Thu 17:37] Ejemplo2_*
     + [2021-05-20 Thu 17:43] Faltan ecuaciones nuevamente.
     + [2021-05-20 Thu 17:44] Mismo procedimiento.
       - [2021-05-20 Thu 17:47] Usa triángulos semejantes para obtener ecuación.





* Local variables :noexport:
  # Local Variables:
  # ispell-local-dictionary: "espanol"
  # End:
