#+TITLE: Probabilidad y Estadística
#+SETUPFILE: ~/Downloads/org-html-themes/setup/theme-readtheorg.setup
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :university:probability:statistics:
# Sources for latex math notation:
# https://en.wikipedia.org/wiki/List_of_mathematical_symbols_by_subject
# https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols
# https://jblevins.org/log/greek

# for probability definition
\[
\def\PP{{\mathbb P}}
\]

# given that
# https://tex.stackexchange.com/questions/141570/sizing-for-given-that-symbol-vertical-bar
\[
\newcommand\given[1][]{\:#1\vert\:}
\]

* Cátedras
** Mon Nov  2 11:32:32 2020
*** TODO Lenguaje de programación
    - R

    [[https://www.youtube.com/results?search_query=R+for+probability+and+statistiscs][youtube: R for probability and statistiscs]]
  
* Material de estudio
** Apuntes libro: Probabilidad y Estadística con Aplicaciones a Ingeniería y Ciencias
   file:~/myDrive/uni/2020-2/proba/

   - Sonia Salvo
   - Antonio Sanhueza Campos
   - Rodrigo Puchi-Ancasay
*** Requisitos
    - Lógica
    - Teoría de Conjuntos
    - Leyes de DeMorgan
*** Capítulo 1: Probabilidad
**** Objetivo
     Introducir nociones básicas de probabilidad
**** Experimento
     Ejecución de instrucciones de la cual se obtiene un resultado.
**** Experimento aleatorio
     - Se conocen todos los posibles resultados.
     - No se conoce el resultado antes de ejecutarlo.
     - Idéntico resultado para idénticas condiciones de ejecución.
***** Ejemplos
      - Lanzar una moneda y observar el resultado.
      - Lanzar \(n\) monedas al aire y observar el resultado de cada una (\(n\ ϵ\ ℕ \)).
      - Lanzar un dado sobre una superficie y observar el número que aparece.
      - Seleccionar aleatoriamente 3 fichas desde una tómbola que contiene fichas (\(n\ >\ 3\)).
      - Registrar la cantidad de accidentes automovilísticos que ocurren diariamente en una ciudad.
      - Seleccionar al azar un punto desde un círculo con centro en el origen y radio 1.
**** Espacio muestral: \Omega

     Conjunto de resultados posibles al ejecutar un experimento.

***** Relación entre eventos
****** Unión
       Ocurre A o B.
       \[
       A \cup B
       \]
****** Intersección
       Ocurre A y B.
       \[
       A \cap B
       \]
****** Subconjunto
       B contiene a A; A está contenido dentro de B, A es subconjunto de B.
       \[
       A \subset B
       \]
       Cabe decir que si ocurre A, entonces ocurre B, pero no viceversa.
**** Evento aleatorio
     Evento asociado a un experimento aleatorio.

     - Leyes de Morgan:

     - Axiomática de álgebra:

     Revisar apunte campus

**** Coeficiente binomial
     # https://tex.stackexchange.com/questions/127707/displaying-the-binomial-coefficient-symbol-in-math-mode
     \[
     \binom{N}{n}
     =
     \left(
     \frac
     {N!}
     {n! (N-n)!}
     \right)
     \]
**** Axiomas de probabilidad
    
     También conocidos como axiomas de \(\mbox{Kolmogorov}\).

     1) \(\PP (A)\geq 0 \)
     2) \(\PP(\Omega)=1 \)
     3) \(A_i \cap A_j = \varnothing \) con \( i\neq j \) ; entonces
     # https://tex.stackexchange.com/questions/205125/formatting-the-union-of-sets
     # https://tex.stackexchange.com/questions/38868/big-parenthesis-in-an-equation
     \[
     \PP
     \left(
     \bigcup
     \limits
     _{i=1}
     ^{\infty}
     A_{i}
     \right)
     =
     \sum
     _{i=1}
     ^\infty
     \PP(A_i).
     \]

     que se lee así:
     #+BEGIN_QUOTE
     "Si los eventos A y B son disjuntos (la intersección es vacía), entonces la probabilidad de la unión de los eventos es igual a la suma de las probabilidades individuales de cada evento".
     #+END_QUOTE

**** Propiedades de la función de probabilidad
     Estas propiedades se demuestran usando los 3 axiomas de probabilidad.
***** del vacío

      "La probabilidad de un evento vacío es cero" … porque la probabilidad de que no ocurra _nada_ en un experimento es nula.
       
      \[
      \PP(\varnothing)=0
      \]
       
***** de eventos disjuntos finitos
      Básicamente lo mismo que el tercer axioma pero a diferencia que esta propiedad especifica un conjunto _finito_ de eventos, mientras que el axioma es para un conjunto _infinito_ de eventos.


      \[
      \PP
      \left(
      \bigcup
      \limits
      _{i=1}
      ^{n}
      A_{i}
      \right)
      =
      \sum
      _{i=1}
      ^n
      \PP(A_i).
      \]

***** de la unión
     
      Aquí, en ningún momento se asume que los eventos son disjuntos. Diagramas de Venn y demostraciones con los axiomas hacen la demostración más evidente, pero aquí solo se presentará la propiedad sin demostración.

      \[
      \PP(A\cup B)=\PP(A)+\PP(B)-\PP(A\cap B).
      \]

      Además, durante la demostración de esta propiedad se desprenden otros ítems que pueden ser útiles:


      \[
      \PP(A)=\PP(A\cap B^c)+\PP(A\cap B). \\
      \PP(B)=\PP(A^c\cap B)+\PP(A\cap B).
      \]

***** del complemento

      \[
      \PP(A^c)=1 - \PP(A).
      \]
     
***** del subconjunto
      # https://tex.stackexchange.com/questions/47063/rightarrow-vs-implies-and-does-not-imply-symbol
      \[
      A \subset B \implies \PP(A) \leq \PP(B).
      \]

      Si A es subconjunto de B, entonces la ocurrencia de A implica la ocurrencia de B, pero no viceversa.

**** Probabilidad Condicional
     # https://tex.stackexchange.com/questions/141570/sizing-for-given-that-symbol-vertical-bar
     Sean A y B eventos tal que \( \PP (B) > 0 \). La probabilidad de que ocurra A dado que ocurrió B se expresa así:

     \[
     \PP (A \given B)
     =
     \frac
     {\PP (A \cap B)}
     {\PP (B)}
     \]

     A partir de aquí se puede obtener también que
    
     \[
     \PP (A \cap B)
     =
     \PP (A \given B)
     \cdot
     \PP (B)
     \]

**** Independencia de eventos
     Si los eventos A y B son independientes, significa que la ocurrencia de uno no afecta las probabilidades de ocurrencia del otro. Luego, mezclándolo con la probabilidad condicional obtenemos la siguiente propiedad de eventos independientes.

     \[
     \PP (A \cap B)
     =
     \PP (A)
     \cdot
     \PP (B)
     \]

     Si la ecuación presentada es verdadera, entonces se dice que los eventos A y B son independientes uno del otro; el hecho que ocurra uno no afecta en lo absoluto la probabilidad de ocurrencia del otro.

     O dicho de otra manera; si los eventos A y B son independientes, entonces la ecuación presentada es verdadera.

     Lo mismo se desprende para los complementos:

     \[
     \PP (A \cap B^c)
     =
     \PP (A)
     \cdot
     \PP (B^c)
     \]

**** Probabilidad Total
     https://www.youtube.com/watch?v=F3y8qupFfUs
**** Teorema de Bayes

     - presentación
     https://www.youtube.com/watch?v=XQoLVl31ZfQ
     - caso un poco mas complicado
     https://www.youtube.com/watch?v=k6Dw0on6NtM
     - caso real
     https://www.youtube.com/watch?v=R13BD8qKeTg
     - por ver
     https://www.youtube.com/watch?v=OByl4RJxnKA

*** Capítulo 2: Variables Aleatorias Unidimensionales
**** Función Generadora de Momentos

     La que te sirve para calcular la Esperanza, Varianza y Desviación Estándar de cualquier función de probabilidad.

**** Esperanza

     #+BEGIN_QUOTE
     La esperanza matemática de una variable aleatoria es una generalización del concepto de media aritmética.
     #+END_QUOTE


     Para una distribución discreta se toma la sumatoria:
     #+BEGIN_CENTER
     \[
     \mu_x=E[X]=\sum x \cdot p(x)
     \]
     #+END_CENTER

     Para una distribución continua se toma la integral:
     #+BEGIN_CENTER
     \[
     \mu_x=E[X]=\int x \cdot f(x) \, dx
     \]
     #+END_CENTER

     \(p(x)\) para una distribución discreta y \(f(x)\) para una distribución continua.

***** Propiedad
      Sea \(g(X)=c_1 + c_2X\) con \(c_1\) y \(c_2\) constantes reales y \(X\) variable aleatoria.
      La esperanza de \(g(X)\) se define como:
      #+BEGIN_CENTER
      \[
      E[g(X)] = E[c_1 + c_2X] = E[c_1] + E[c_2X] = c_1 + c_2 E[X]
      \]
      #+END_CENTER

**** Varianza
    
     #+BEGIN_QUOTE
     La varianza indica la dispersión de la distribución de la variable aleatoria, lo que permite contar con una medida de cuán homogénea (menor dispersión) o heterogénea (mayor dispersión) es la variable.
     #+END_QUOTE

     Se define la varianza de una variable aleatoria:

     #+BEGIN_CENTER
     \[
     Var[X]=E[(X-E[X])^2]
     \]
     #+END_CENTER

     Y si hacemos el desarrollo algebraico, podemos llegar a una notación más conveniente:

     #+BEGIN_CENTER
     \[
     Var[X]=E[X^2] - (E[X])^2
     \]
     #+END_CENTER

     por lo que para el análisis usual en un curso de Probabilidad y Estadística para Ingeniería Civil, es conveniente tener a mano los términos \(E[X]\) y \(E[X^2]\) para el calculo de diferentes parámetros.

***** Propiedad
      Sea \(k\) una constante real y \(X\) una variable aleatoria:
      \begin{align*}
          Var[k] &= 0 \\
          Var[kX] &= k^2 Var[X]
      \end{align*}

**** Desviación Estándar

* Horario de clases :schedule:
** Lunes 10:50
   https://reuna.zoom.us/j/85122697353?pwd=QlhoQis3Yld6U1cwa1RCZ3p1U0ZOQT09

** Miércoles 10:50
   https://reuna.zoom.us/j/89121593711?pwd=TTk1OFBEVERkZlRzbWkxM0gzaW9GUT09

** Cápsula lunes 16:00
   https://reuna.zoom.us/j/86980024556?pwd=TWh3Zjh6cmZGRmVhckZPeVJLRElRQT09

** Cápsula jueves 19:00
   https://reuna.zoom.us/j/84436682992?pwd=bGMxRWpWVi9ILzNXbzMvOC9Ya2F3QT09

** Discord:
   https://discord.gg/efGbyAUd

** Insta:
   https://www.instagram.com/clinicamat_ufro/
 
* Evaluación :exam:

  - Alternativas.
  - Sincrónica.

  - (.7) teórica & (.3) práctica (campus)

** TODO Actividades Campus
** DONE 18 nov (.30)
   CLOSED: [2020-11-23 Mon 18:03]
   :LOGBOOK:
   - State "DONE"       from              [2020-11-23 Mon 18:03]
   :END:
** DONE [#A] 23 dic (.35)
   CLOSED: [2020-12-27 Sun 15:53]
   :LOGBOOK:
   - State "DONE"       from "TODO"       [2020-12-27 Sun 15:53]
   :END:
** TODO 27 ene (.35)
* Contacto
** sonia.salvo@ufrontera.cl
* Vocabulario
  - sistemas estocásticos
* Local variables :noexport:
  # Local Variables:
  # ispell-local-dictionary: "espanol"
  # End:
