#+TITLE: Mecánica de Fluidos
#+SETUPFILE: ~/Downloads/org-html-themes/setup/theme-readtheorg.setup
#+EXCLUDE_TAGS: noexport
#+FILETAGS: :university:
# latex goodies
# spacing
# https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing
# nice looking emptyset
# https://tex.stackexchange.com/questions/22798/nice-looking-empty-set

* Mecánica de Fluidos
** Evaluación :exam:
*** prueba1

    #+BEGIN_QUOTE
    Estimados estudiantes de acuerdo con lo que el curso acordó, el martes 24 de noviembre es la primera prueba de Mecánica de Fluidos.

    El temas:

    1. Cálculo de Fuerzas sobre paredes planas
    2. Cálculo de Centros de presión.

    Con las pautas enviadas anteriormente, es suficiente para presentarse a la prueba.
    #+END_QUOTE


    Las pautas:
    file:~/myDrive/files/uni/2020-2/mecanica-de-fluidos/prueba1/

**** Apuntes
***** Capitulo 1: Unidades de Medida utilizadas en diseños ingenieriles
      Repaso de unidades de medida.
***** Capitulo 2: Generalidades de la mecánica de fluidos.
****** Densidad específica (o absoluta)

       \[
       \rho
       =
       \frac
       {m}
       {V}
       =
       \frac
       {[\,kg\,]}
       {[\,m^3\,]}
       \]

****** Peso específico

       \[
       \gamma
       =
       \frac
       {m\cdot g}
       {V}
       \quad
       \rightarrow
       \quad
       \gamma
       =
       g\cdot \rho
       \quad
       ;
       \quad
       m \cdot g = W
       \]

       \[
       [\,\gamma\,]
       =
       \frac
       {[\,N\,]}
       {[\,m^\,3]}
       \]

****** Densidad relativa

       Se mide respecto de la densidad del agua.

       \[
       \delta
       =
       \frac
       {W_{substancia}}
       {W_{agua}}
       =
       \frac
       {\rho_{substancia}}
       {\rho_{agua}}
       =
       \frac
       {\gamma_{substancia}}
       {\gamma_{agua}}
       \]

       Es prudente decir que esta medida no tiene unidad, pues habla de la relación entre dos entes de misma dimensión.

       \[
       [\,\delta\,]
       =
       \varnothing
       \]

****** Viscosidad dinámica
       Puede definirse como la resistencia de un fluido a fluir. Se analizan las fuerzas involucradas.
****** Viscosidad cinemática
       Mas menos misma historia, pero ahora se analiza el movimiento del fluido.

****** Notaciones convenientes
      #+begin_center
      \[
      P = \frac{F}{A} = \gamma \cdot h
      = \rho \cdot g \cdot h
      \]

      donde \(h\) es la altura del fluido encima del punto de medición.
      #+end_center

***** Capitulo 3: Hidrostática
      (Supongo que el capítulo 4 se tratará sobre hidrodinámica.)
*** DONE prueba2
    CLOSED: [2021-01-19 Tue 17:00]
    :LOGBOOK:
    - State "DONE"       from "TODO"       [2021-01-19 Tue 17:00] \\
      For the blue, but could have been even better; how to get the pressure when you have the flow?
    :END:
    <2021-01-19 Tue 10:50>
    Bernulli, sin pérdidas.
**** 30 noviembre
***** Hidrodinámica
****** Bernoulli Ideal
       #+begin_center
       Ecuación de Bernulli sin perdidas: Ideal \\
       Ecuación Fundamental de la Hidrodinámica.
       \begin{align*}
       \frac{P_1}{\gamma}
       +
       \frac{V_1^2}{2g}
       +
       z_1
       &=
       \frac{P_2}{\gamma}
       +
       \frac{V_2^2}{2g}
       +
       z_2
       =
       H
       \end{align*}

       donde \(\gamma = \rho \cdot g\ \).
       #+end_center

       - \(P/\gamma\ \) se conoce como /altura de presión/ o /altura específica/ o /energía específica de presión/.
       - \( V^2/2g \) se conoce como /velocidad de presión/ o /altura dinámica/ o /altura de velocidades/.
       - \( z \) se conoce como /altura geodésica/: la distancia medida desde la superficie de la Tiera.

         Bernoulli Generalizado
*** TODO prueba3
    <2021-02-01 Mon>
** Links
*** Cátedra y ayudantía
    - https://reuna.zoom.us/j/88660177029?pwd=d3FBVE1vdjQ1Q012OEt6SDMvOXRUdz09
*** Clases grabadas
    https://drive.google.com/drive/folders/1JczG_zXbs9rUVke_3bZdGdAXDVdgBArk
** Contacto
   Mario Guzmán
** Local variables :noexport:
   # Local Variables:
   # ispell-local-dictionary: "espanol"
   # End:
